// GENERATED by @BBeBee/tooling-gen-plugins — do not edit.
// Run `pnpm gen:plugins` to refresh.

import type { PluginManifest } from '@BBeBee/protocol'

export const PLUGIN_MANIFESTS: Record<string, PluginManifest> = {
  "@BBeBee/core-audio-mpv": {
    "id": "@BBeBee/core-audio-mpv",
    "name": "@BBeBee/core-audio-mpv",
    "displayName": "Audio (Desktop MPV)",
    "description": "ctx.audio — libmpv audio engine with native audio-engine crash isolation, direct WASAPI output, native DSP/EQ, and FFT visualizer.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [],
    "systemId": "layer-2",
    "moduleId": "playback",
    "platforms": [
      "desktop"
    ],
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [
      "audio"
    ],
    "contributes": {
      "services": [
        "audio"
      ]
    }
  },
  "core-audio-mpv": {
    "id": "@BBeBee/core-audio-mpv",
    "name": "@BBeBee/core-audio-mpv",
    "displayName": "Audio (Desktop MPV)",
    "description": "ctx.audio — libmpv audio engine with native audio-engine crash isolation, direct WASAPI output, native DSP/EQ, and FFT visualizer.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [],
    "systemId": "layer-2",
    "moduleId": "playback",
    "platforms": [
      "desktop"
    ],
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [
      "audio"
    ],
    "contributes": {
      "services": [
        "audio"
      ]
    }
  },
  "@BBeBee/core-audio-webaudio": {
    "id": "@BBeBee/core-audio-webaudio",
    "name": "@BBeBee/core-audio-webaudio",
    "displayName": "Audio",
    "description": "ctx.audio — the Web Audio graph, shared by every target.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [],
    "systemId": "layer-2",
    "moduleId": "playback",
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [
      "audio"
    ],
    "contributes": {
      "services": [
        "audio"
      ]
    }
  },
  "core-audio-webaudio": {
    "id": "@BBeBee/core-audio-webaudio",
    "name": "@BBeBee/core-audio-webaudio",
    "displayName": "Audio",
    "description": "ctx.audio — the Web Audio graph, shared by every target.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [],
    "systemId": "layer-2",
    "moduleId": "playback",
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [
      "audio"
    ],
    "contributes": {
      "services": [
        "audio"
      ]
    }
  },
  "@BBeBee/core-background-electron": {
    "id": "@BBeBee/core-background-electron",
    "name": "@BBeBee/core-background-electron",
    "displayName": "Background",
    "description": "ctx.background — wake locks, scheduling and suspend hooks on desktop.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [],
    "systemId": "layer-2",
    "moduleId": "core",
    "platforms": [
      "desktop"
    ],
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [
      "background"
    ],
    "contributes": {
      "services": [
        "background"
      ]
    }
  },
  "core-background-electron": {
    "id": "@BBeBee/core-background-electron",
    "name": "@BBeBee/core-background-electron",
    "displayName": "Background",
    "description": "ctx.background — wake locks, scheduling and suspend hooks on desktop.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [],
    "systemId": "layer-2",
    "moduleId": "core",
    "platforms": [
      "desktop"
    ],
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [
      "background"
    ],
    "contributes": {
      "services": [
        "background"
      ]
    }
  },
  "@BBeBee/core-background-expo": {
    "id": "@BBeBee/core-background-expo",
    "name": "@BBeBee/core-background-expo",
    "displayName": "Background",
    "description": "ctx.background for iOS and Android — audio session, wake locks, deferred work.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [],
    "systemId": "layer-2",
    "moduleId": "core",
    "platforms": [
      "mobile"
    ],
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [
      "background"
    ],
    "contributes": {
      "services": [
        "background"
      ]
    }
  },
  "core-background-expo": {
    "id": "@BBeBee/core-background-expo",
    "name": "@BBeBee/core-background-expo",
    "displayName": "Background",
    "description": "ctx.background for iOS and Android — audio session, wake locks, deferred work.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [],
    "systemId": "layer-2",
    "moduleId": "core",
    "platforms": [
      "mobile"
    ],
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [
      "background"
    ],
    "contributes": {
      "services": [
        "background"
      ]
    }
  },
  "@BBeBee/core-codec-node": {
    "id": "@BBeBee/core-codec-node",
    "name": "@BBeBee/core-codec-node",
    "displayName": "Codec",
    "description": "ctx.codec — tags, artwork and PCM, over music-metadata.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [],
    "systemId": "layer-2",
    "moduleId": "core",
    "platforms": [
      "desktop"
    ],
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [
      "fs:read:all"
    ],
    "contributes": {
      "services": [
        "codec"
      ]
    }
  },
  "core-codec-node": {
    "id": "@BBeBee/core-codec-node",
    "name": "@BBeBee/core-codec-node",
    "displayName": "Codec",
    "description": "ctx.codec — tags, artwork and PCM, over music-metadata.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [],
    "systemId": "layer-2",
    "moduleId": "core",
    "platforms": [
      "desktop"
    ],
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [
      "fs:read:all"
    ],
    "contributes": {
      "services": [
        "codec"
      ]
    }
  },
  "@BBeBee/core-codec-rn": {
    "id": "@BBeBee/core-codec-rn",
    "name": "@BBeBee/core-codec-rn",
    "displayName": "Codec",
    "description": "ctx.codec for iOS and Android — tags over ctx.fs, PCM via AudioDecoder.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [],
    "systemId": "layer-2",
    "moduleId": "core",
    "platforms": [
      "mobile"
    ],
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [
      "fs:read:all"
    ],
    "contributes": {
      "services": [
        "codec"
      ]
    }
  },
  "core-codec-rn": {
    "id": "@BBeBee/core-codec-rn",
    "name": "@BBeBee/core-codec-rn",
    "displayName": "Codec",
    "description": "ctx.codec for iOS and Android — tags over ctx.fs, PCM via AudioDecoder.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [],
    "systemId": "layer-2",
    "moduleId": "core",
    "platforms": [
      "mobile"
    ],
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [
      "fs:read:all"
    ],
    "contributes": {
      "services": [
        "codec"
      ]
    }
  },
  "@BBeBee/core-device-electron": {
    "id": "@BBeBee/core-device-electron",
    "name": "@BBeBee/core-device-electron",
    "displayName": "Device",
    "description": "ctx.device — network, battery, media keys and hotkeys on desktop.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [],
    "systemId": "layer-2",
    "moduleId": "core",
    "platforms": [
      "desktop"
    ],
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [],
    "contributes": {
      "services": [
        "device"
      ]
    }
  },
  "core-device-electron": {
    "id": "@BBeBee/core-device-electron",
    "name": "@BBeBee/core-device-electron",
    "displayName": "Device",
    "description": "ctx.device — network, battery, media keys and hotkeys on desktop.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [],
    "systemId": "layer-2",
    "moduleId": "core",
    "platforms": [
      "desktop"
    ],
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [],
    "contributes": {
      "services": [
        "device"
      ]
    }
  },
  "@BBeBee/core-device-expo": {
    "id": "@BBeBee/core-device-expo",
    "name": "@BBeBee/core-device-expo",
    "displayName": "Device",
    "description": "ctx.device for iOS and Android — network, battery, locale.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [],
    "systemId": "layer-2",
    "moduleId": "core",
    "platforms": [
      "mobile"
    ],
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [],
    "contributes": {
      "services": [
        "device"
      ]
    }
  },
  "core-device-expo": {
    "id": "@BBeBee/core-device-expo",
    "name": "@BBeBee/core-device-expo",
    "displayName": "Device",
    "description": "ctx.device for iOS and Android — network, battery, locale.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [],
    "systemId": "layer-2",
    "moduleId": "core",
    "platforms": [
      "mobile"
    ],
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [],
    "contributes": {
      "services": [
        "device"
      ]
    }
  },
  "@BBeBee/core-http-node": {
    "id": "@BBeBee/core-http-node",
    "name": "@BBeBee/core-http-node",
    "displayName": "HTTP",
    "description": "ctx.http — outbound HTTP, the M1 slice.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [],
    "systemId": "layer-2",
    "moduleId": "core",
    "platforms": [
      "desktop"
    ],
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [
      "net:host/*",
      "fs:write:downloads"
    ],
    "contributes": {
      "services": [
        "http"
      ]
    }
  },
  "core-http-node": {
    "id": "@BBeBee/core-http-node",
    "name": "@BBeBee/core-http-node",
    "displayName": "HTTP",
    "description": "ctx.http — outbound HTTP, the M1 slice.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [],
    "systemId": "layer-2",
    "moduleId": "core",
    "platforms": [
      "desktop"
    ],
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [
      "net:host/*",
      "fs:write:downloads"
    ],
    "contributes": {
      "services": [
        "http"
      ]
    }
  },
  "@BBeBee/core-http-rn": {
    "id": "@BBeBee/core-http-rn",
    "name": "@BBeBee/core-http-rn",
    "displayName": "HTTP",
    "description": "ctx.http for iOS and Android — the M1 slice over expo/fetch.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [],
    "systemId": "layer-2",
    "moduleId": "core",
    "platforms": [
      "mobile"
    ],
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [
      "net:host/*"
    ],
    "contributes": {
      "services": [
        "http"
      ]
    }
  },
  "core-http-rn": {
    "id": "@BBeBee/core-http-rn",
    "name": "@BBeBee/core-http-rn",
    "displayName": "HTTP",
    "description": "ctx.http for iOS and Android — the M1 slice over expo/fetch.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [],
    "systemId": "layer-2",
    "moduleId": "core",
    "platforms": [
      "mobile"
    ],
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [
      "net:host/*"
    ],
    "contributes": {
      "services": [
        "http"
      ]
    }
  },
  "@BBeBee/core-js-quickjs-node": {
    "id": "@BBeBee/core-js-quickjs-node",
    "name": "@BBeBee/core-js-quickjs-node",
    "displayName": "Script sandbox",
    "description": "ctx.js — a QuickJS realm per source, for desktop and Node.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [],
    "systemId": "layer-2",
    "moduleId": "core",
    "platforms": [
      "desktop"
    ],
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [],
    "contributes": {
      "services": [
        "js"
      ]
    }
  },
  "core-js-quickjs-node": {
    "id": "@BBeBee/core-js-quickjs-node",
    "name": "@BBeBee/core-js-quickjs-node",
    "displayName": "Script sandbox",
    "description": "ctx.js — a QuickJS realm per source, for desktop and Node.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [],
    "systemId": "layer-2",
    "moduleId": "core",
    "platforms": [
      "desktop"
    ],
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [],
    "contributes": {
      "services": [
        "js"
      ]
    }
  },
  "@BBeBee/core-media-session-electron": {
    "id": "@BBeBee/core-media-session-electron",
    "name": "@BBeBee/core-media-session-electron",
    "displayName": "Media session",
    "description": "ctx.mediaSession — the OS now-playing surface on desktop.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [],
    "systemId": "layer-2",
    "moduleId": "core",
    "platforms": [
      "desktop"
    ],
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [
      "mediaSession"
    ],
    "contributes": {
      "services": [
        "mediaSession"
      ]
    }
  },
  "core-media-session-electron": {
    "id": "@BBeBee/core-media-session-electron",
    "name": "@BBeBee/core-media-session-electron",
    "displayName": "Media session",
    "description": "ctx.mediaSession — the OS now-playing surface on desktop.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [],
    "systemId": "layer-2",
    "moduleId": "core",
    "platforms": [
      "desktop"
    ],
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [
      "mediaSession"
    ],
    "contributes": {
      "services": [
        "mediaSession"
      ]
    }
  },
  "@BBeBee/core-media-session-rn": {
    "id": "@BBeBee/core-media-session-rn",
    "name": "@BBeBee/core-media-session-rn",
    "displayName": "Media Session",
    "description": "ctx.mediaSession for iOS and Android — lock screen and media notification.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [],
    "systemId": "layer-2",
    "moduleId": "core",
    "platforms": [
      "mobile"
    ],
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [
      "mediaSession"
    ],
    "contributes": {
      "services": [
        "mediaSession"
      ]
    }
  },
  "core-media-session-rn": {
    "id": "@BBeBee/core-media-session-rn",
    "name": "@BBeBee/core-media-session-rn",
    "displayName": "Media Session",
    "description": "ctx.mediaSession for iOS and Android — lock screen and media notification.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [],
    "systemId": "layer-2",
    "moduleId": "core",
    "platforms": [
      "mobile"
    ],
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [
      "mediaSession"
    ],
    "contributes": {
      "services": [
        "mediaSession"
      ]
    }
  },
  "@BBeBee/core-secrets-expo": {
    "id": "@BBeBee/core-secrets-expo",
    "name": "@BBeBee/core-secrets-expo",
    "displayName": "Secrets",
    "description": "ctx.secrets for iOS and Android, over expo-secure-store.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [],
    "systemId": "layer-2",
    "moduleId": "core",
    "platforms": [
      "mobile"
    ],
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [],
    "contributes": {
      "services": [
        "secrets"
      ]
    }
  },
  "core-secrets-expo": {
    "id": "@BBeBee/core-secrets-expo",
    "name": "@BBeBee/core-secrets-expo",
    "displayName": "Secrets",
    "description": "ctx.secrets for iOS and Android, over expo-secure-store.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [],
    "systemId": "layer-2",
    "moduleId": "core",
    "platforms": [
      "mobile"
    ],
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [],
    "contributes": {
      "services": [
        "secrets"
      ]
    }
  },
  "@BBeBee/core-secrets-node": {
    "id": "@BBeBee/core-secrets-node",
    "name": "@BBeBee/core-secrets-node",
    "displayName": "Secrets",
    "description": "ctx.secrets — credential storage for desktop and Node.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [],
    "systemId": "layer-2",
    "moduleId": "core",
    "platforms": [
      "desktop"
    ],
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [
      "fs:read:own",
      "fs:write:own"
    ],
    "contributes": {
      "services": [
        "secrets"
      ]
    }
  },
  "core-secrets-node": {
    "id": "@BBeBee/core-secrets-node",
    "name": "@BBeBee/core-secrets-node",
    "displayName": "Secrets",
    "description": "ctx.secrets — credential storage for desktop and Node.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [],
    "systemId": "layer-2",
    "moduleId": "core",
    "platforms": [
      "desktop"
    ],
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [
      "fs:read:own",
      "fs:write:own"
    ],
    "contributes": {
      "services": [
        "secrets"
      ]
    }
  },
  "@BBeBee/plugin-album": {
    "id": "@BBeBee/plugin-album",
    "name": "@BBeBee/plugin-album",
    "displayName": "Album",
    "description": "The album page — detail, tracks, and album-level actions.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-sources"
    ],
    "systemId": "layer-4",
    "moduleId": "storage",
    "entry": {
      "main": "./dist/index.js",
      "ui": {
        "desktop": "./dist/index.js",
        "mobile": "./dist/index.js"
      }
    },
    "capabilities": [],
    "contributes": {}
  },
  "plugin-album": {
    "id": "@BBeBee/plugin-album",
    "name": "@BBeBee/plugin-album",
    "displayName": "Album",
    "description": "The album page — detail, tracks, and album-level actions.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-sources"
    ],
    "systemId": "layer-4",
    "moduleId": "storage",
    "entry": {
      "main": "./dist/index.js",
      "ui": {
        "desktop": "./dist/index.js",
        "mobile": "./dist/index.js"
      }
    },
    "capabilities": [],
    "contributes": {}
  },
  "@BBeBee/plugin-cache": {
    "id": "@BBeBee/plugin-cache",
    "name": "@BBeBee/plugin-cache",
    "displayName": "Cache",
    "description": "ctx.cache — covers and remote audio streams are served from disk, and fetched only on a miss.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [],
    "systemId": "layer-4",
    "moduleId": "storage",
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [
      "net:host/*",
      "fs:read:cache",
      "fs:write:cache",
      "db:read:core",
      "db:write:core"
    ],
    "contributes": {
      "services": [
        "cache"
      ]
    }
  },
  "plugin-cache": {
    "id": "@BBeBee/plugin-cache",
    "name": "@BBeBee/plugin-cache",
    "displayName": "Cache",
    "description": "ctx.cache — covers and remote audio streams are served from disk, and fetched only on a miss.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [],
    "systemId": "layer-4",
    "moduleId": "storage",
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [
      "net:host/*",
      "fs:read:cache",
      "fs:write:cache",
      "db:read:core",
      "db:write:core"
    ],
    "contributes": {
      "services": [
        "cache"
      ]
    }
  },
  "@BBeBee/plugin-desktop-lyrics": {
    "id": "@BBeBee/plugin-desktop-lyrics",
    "name": "@BBeBee/plugin-desktop-lyrics",
    "displayName": "Desktop Lyrics",
    "description": "Floating desktop lyrics state and command contributions.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-lyrics"
    ],
    "systemId": "layer-4",
    "moduleId": "lyrics",
    "entry": {
      "main": "./dist/index.js",
      "ui": {
        "desktop": "./dist/index.js"
      }
    },
    "capabilities": [],
    "contributes": {
      "services": [
        "desktopLyrics"
      ]
    }
  },
  "plugin-desktop-lyrics": {
    "id": "@BBeBee/plugin-desktop-lyrics",
    "name": "@BBeBee/plugin-desktop-lyrics",
    "displayName": "Desktop Lyrics",
    "description": "Floating desktop lyrics state and command contributions.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-lyrics"
    ],
    "systemId": "layer-4",
    "moduleId": "lyrics",
    "entry": {
      "main": "./dist/index.js",
      "ui": {
        "desktop": "./dist/index.js"
      }
    },
    "capabilities": [],
    "contributes": {
      "services": [
        "desktopLyrics"
      ]
    }
  },
  "@BBeBee/plugin-desktop-taskbar": {
    "id": "@BBeBee/plugin-desktop-taskbar",
    "name": "@BBeBee/plugin-desktop-taskbar",
    "displayName": "Desktop Taskbar",
    "description": "Desktop taskbar and tray playback controls for Play/Pause, Previous, and Next.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-player"
    ],
    "systemId": "layer-4",
    "moduleId": "playback",
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [],
    "contributes": {}
  },
  "plugin-desktop-taskbar": {
    "id": "@BBeBee/plugin-desktop-taskbar",
    "name": "@BBeBee/plugin-desktop-taskbar",
    "displayName": "Desktop Taskbar",
    "description": "Desktop taskbar and tray playback controls for Play/Pause, Previous, and Next.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-player"
    ],
    "systemId": "layer-4",
    "moduleId": "playback",
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [],
    "contributes": {}
  },
  "@BBeBee/plugin-download": {
    "id": "@BBeBee/plugin-download",
    "name": "@BBeBee/plugin-download",
    "displayName": "Downloads",
    "description": "ctx.downloads — the managed download queue.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-sources"
    ],
    "systemId": "layer-4",
    "moduleId": "storage",
    "entry": {
      "main": "./dist/index.js",
      "ui": {
        "desktop": "./dist/index.js",
        "mobile": "./dist/index.js"
      }
    },
    "capabilities": [
      "net:host/*",
      "fs:read:cache",
      "fs:write:cache",
      "fs:read:downloads",
      "fs:write:downloads",
      "db:read:core",
      "db:write:core"
    ],
    "contributes": {
      "services": [
        "downloads"
      ]
    }
  },
  "plugin-download": {
    "id": "@BBeBee/plugin-download",
    "name": "@BBeBee/plugin-download",
    "displayName": "Downloads",
    "description": "ctx.downloads — the managed download queue.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-sources"
    ],
    "systemId": "layer-4",
    "moduleId": "storage",
    "entry": {
      "main": "./dist/index.js",
      "ui": {
        "desktop": "./dist/index.js",
        "mobile": "./dist/index.js"
      }
    },
    "capabilities": [
      "net:host/*",
      "fs:read:cache",
      "fs:write:cache",
      "fs:read:downloads",
      "fs:write:downloads",
      "db:read:core",
      "db:write:core"
    ],
    "contributes": {
      "services": [
        "downloads"
      ]
    }
  },
  "@BBeBee/plugin-dsp": {
    "id": "@BBeBee/plugin-dsp",
    "name": "@BBeBee/plugin-dsp",
    "displayName": "DSP Effect Chain",
    "description": "ctx.dsp — effect chain builder, presets, and audio processing effects.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-player"
    ],
    "systemId": "layer-4",
    "moduleId": "dsp",
    "entry": {
      "main": "./dist/index.js",
      "ui": {
        "desktop": "./dist/index.js",
        "mobile": "./dist/index.js"
      }
    },
    "capabilities": [
      "audio"
    ],
    "contributes": {
      "services": [
        "dsp"
      ]
    }
  },
  "plugin-dsp": {
    "id": "@BBeBee/plugin-dsp",
    "name": "@BBeBee/plugin-dsp",
    "displayName": "DSP Effect Chain",
    "description": "ctx.dsp — effect chain builder, presets, and audio processing effects.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-player"
    ],
    "systemId": "layer-4",
    "moduleId": "dsp",
    "entry": {
      "main": "./dist/index.js",
      "ui": {
        "desktop": "./dist/index.js",
        "mobile": "./dist/index.js"
      }
    },
    "capabilities": [
      "audio"
    ],
    "contributes": {
      "services": [
        "dsp"
      ]
    }
  },
  "@BBeBee/plugin-history": {
    "id": "@BBeBee/plugin-history",
    "name": "@BBeBee/plugin-history",
    "displayName": "Play History",
    "description": "Play history and statistics — a view of the playback history ctx.player owns.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-player"
    ],
    "systemId": "layer-4",
    "moduleId": "storage",
    "entry": {
      "main": "./dist/index.js",
      "ui": {
        "desktop": "./dist/index.js",
        "mobile": "./dist/index.js"
      }
    },
    "capabilities": [],
    "contributes": {}
  },
  "plugin-history": {
    "id": "@BBeBee/plugin-history",
    "name": "@BBeBee/plugin-history",
    "displayName": "Play History",
    "description": "Play history and statistics — a view of the playback history ctx.player owns.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-player"
    ],
    "systemId": "layer-4",
    "moduleId": "storage",
    "entry": {
      "main": "./dist/index.js",
      "ui": {
        "desktop": "./dist/index.js",
        "mobile": "./dist/index.js"
      }
    },
    "capabilities": [],
    "contributes": {}
  },
  "@BBeBee/plugin-inspector": {
    "id": "@BBeBee/plugin-inspector",
    "name": "@BBeBee/plugin-inspector",
    "displayName": "Plugin Inspector",
    "description": "Fiber tree and labelled effects.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [],
    "systemId": "layer-4",
    "moduleId": "inspector",
    "entry": {
      "main": "./dist/index.js",
      "ui": {
        "desktop": "./dist/index.js"
      }
    },
    "capabilities": [],
    "contributes": {
      "services": [
        "inspector"
      ]
    }
  },
  "plugin-inspector": {
    "id": "@BBeBee/plugin-inspector",
    "name": "@BBeBee/plugin-inspector",
    "displayName": "Plugin Inspector",
    "description": "Fiber tree and labelled effects.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [],
    "systemId": "layer-4",
    "moduleId": "inspector",
    "entry": {
      "main": "./dist/index.js",
      "ui": {
        "desktop": "./dist/index.js"
      }
    },
    "capabilities": [],
    "contributes": {
      "services": [
        "inspector"
      ]
    }
  },
  "@BBeBee/plugin-library": {
    "id": "@BBeBee/plugin-library",
    "name": "@BBeBee/plugin-library",
    "displayName": "Library",
    "description": "ctx.library — playlists, favourites, collections and smart playlists.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-sources"
    ],
    "systemId": "layer-4",
    "moduleId": "storage",
    "entry": {
      "main": "./dist/index.js",
      "ui": {
        "desktop": "./dist/index.js",
        "mobile": "./dist/index.js"
      }
    },
    "capabilities": [
      "db:read:core",
      "db:write:core"
    ],
    "contributes": {
      "services": [
        "library"
      ]
    }
  },
  "plugin-library": {
    "id": "@BBeBee/plugin-library",
    "name": "@BBeBee/plugin-library",
    "displayName": "Library",
    "description": "ctx.library — playlists, favourites, collections and smart playlists.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-sources"
    ],
    "systemId": "layer-4",
    "moduleId": "storage",
    "entry": {
      "main": "./dist/index.js",
      "ui": {
        "desktop": "./dist/index.js",
        "mobile": "./dist/index.js"
      }
    },
    "capabilities": [
      "db:read:core",
      "db:write:core"
    ],
    "contributes": {
      "services": [
        "library"
      ]
    }
  },
  "@BBeBee/plugin-local-scanner": {
    "id": "@BBeBee/plugin-local-scanner",
    "name": "@BBeBee/plugin-local-scanner",
    "displayName": "Local Scanner",
    "description": "ctx.scanner — the local filesystem walk.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-sources"
    ],
    "systemId": "layer-4",
    "moduleId": "storage",
    "entry": {
      "main": "./dist/index.js",
      "ui": {
        "desktop": "./dist/index.js",
        "mobile": "./dist/index.js"
      }
    },
    "capabilities": [
      "fs:read:media",
      "fs:read:all",
      "fs:read:cache",
      "fs:write:cache",
      "db:read:core",
      "db:write:core",
      "background"
    ],
    "contributes": {
      "services": [
        "scanner"
      ]
    }
  },
  "plugin-local-scanner": {
    "id": "@BBeBee/plugin-local-scanner",
    "name": "@BBeBee/plugin-local-scanner",
    "displayName": "Local Scanner",
    "description": "ctx.scanner — the local filesystem walk.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-sources"
    ],
    "systemId": "layer-4",
    "moduleId": "storage",
    "entry": {
      "main": "./dist/index.js",
      "ui": {
        "desktop": "./dist/index.js",
        "mobile": "./dist/index.js"
      }
    },
    "capabilities": [
      "fs:read:media",
      "fs:read:all",
      "fs:read:cache",
      "fs:write:cache",
      "db:read:core",
      "db:write:core",
      "background"
    ],
    "contributes": {
      "services": [
        "scanner"
      ]
    }
  },
  "@BBeBee/plugin-lyric-sources": {
    "id": "@BBeBee/plugin-lyric-sources",
    "name": "@BBeBee/plugin-lyric-sources",
    "displayName": "Lyric Sources",
    "description": "ctx.lyricSources — third-party lyric source provider management and sandboxed execution.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-lyrics"
    ],
    "systemId": "layer-4",
    "moduleId": "lyrics",
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [
      "net:host/*",
      "js"
    ],
    "contributes": {
      "services": [
        "lyricSources"
      ]
    }
  },
  "plugin-lyric-sources": {
    "id": "@BBeBee/plugin-lyric-sources",
    "name": "@BBeBee/plugin-lyric-sources",
    "displayName": "Lyric Sources",
    "description": "ctx.lyricSources — third-party lyric source provider management and sandboxed execution.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-lyrics"
    ],
    "systemId": "layer-4",
    "moduleId": "lyrics",
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [
      "net:host/*",
      "js"
    ],
    "contributes": {
      "services": [
        "lyricSources"
      ]
    }
  },
  "@BBeBee/plugin-lyrics": {
    "id": "@BBeBee/plugin-lyrics",
    "name": "@BBeBee/plugin-lyrics",
    "displayName": "Lyrics",
    "description": "ctx.lyrics — lyric retrieval, caching, synchronization and unified state.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-player"
    ],
    "systemId": "layer-4",
    "moduleId": "lyrics",
    "entry": {
      "main": "./dist/index.js",
      "ui": {
        "desktop": "./dist/index.js"
      }
    },
    "capabilities": [
      "db:read:core",
      "db:write:core"
    ],
    "contributes": {
      "services": [
        "lyrics"
      ]
    }
  },
  "plugin-lyrics": {
    "id": "@BBeBee/plugin-lyrics",
    "name": "@BBeBee/plugin-lyrics",
    "displayName": "Lyrics",
    "description": "ctx.lyrics — lyric retrieval, caching, synchronization and unified state.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-player"
    ],
    "systemId": "layer-4",
    "moduleId": "lyrics",
    "entry": {
      "main": "./dist/index.js",
      "ui": {
        "desktop": "./dist/index.js"
      }
    },
    "capabilities": [
      "db:read:core",
      "db:write:core"
    ],
    "contributes": {
      "services": [
        "lyrics"
      ]
    }
  },
  "@BBeBee/plugin-mini-player": {
    "id": "@BBeBee/plugin-mini-player",
    "name": "@BBeBee/plugin-mini-player",
    "displayName": "Mini Player",
    "description": "Floating mini window and Dynamic Island player controls.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-player"
    ],
    "systemId": "layer-4",
    "moduleId": "playback",
    "entry": {
      "main": "./dist/index.js",
      "ui": {
        "desktop": "./dist/index.js"
      }
    },
    "capabilities": [],
    "contributes": {
      "services": [
        "miniPlayer"
      ]
    }
  },
  "plugin-mini-player": {
    "id": "@BBeBee/plugin-mini-player",
    "name": "@BBeBee/plugin-mini-player",
    "displayName": "Mini Player",
    "description": "Floating mini window and Dynamic Island player controls.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-player"
    ],
    "systemId": "layer-4",
    "moduleId": "playback",
    "entry": {
      "main": "./dist/index.js",
      "ui": {
        "desktop": "./dist/index.js"
      }
    },
    "capabilities": [],
    "contributes": {
      "services": [
        "miniPlayer"
      ]
    }
  },
  "@BBeBee/plugin-now-playing": {
    "id": "@BBeBee/plugin-now-playing",
    "name": "@BBeBee/plugin-now-playing",
    "displayName": "Now playing",
    "description": "The full-screen player and the persistent bar that opens it.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-player"
    ],
    "systemId": "layer-4",
    "moduleId": "playback",
    "entry": {
      "main": "./dist/index.js",
      "ui": {
        "desktop": "./dist/index.js",
        "mobile": "./dist/index.js"
      }
    },
    "capabilities": [],
    "contributes": {
      "services": [
        "nowPlaying"
      ]
    }
  },
  "plugin-now-playing": {
    "id": "@BBeBee/plugin-now-playing",
    "name": "@BBeBee/plugin-now-playing",
    "displayName": "Now playing",
    "description": "The full-screen player and the persistent bar that opens it.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-player"
    ],
    "systemId": "layer-4",
    "moduleId": "playback",
    "entry": {
      "main": "./dist/index.js",
      "ui": {
        "desktop": "./dist/index.js",
        "mobile": "./dist/index.js"
      }
    },
    "capabilities": [],
    "contributes": {
      "services": [
        "nowPlaying"
      ]
    }
  },
  "@BBeBee/plugin-player": {
    "id": "@BBeBee/plugin-player",
    "name": "@BBeBee/plugin-player",
    "displayName": "Player",
    "description": "ctx.player — transport, queue, resolution, history.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-sources"
    ],
    "systemId": "layer-4",
    "moduleId": "playback",
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [
      "audio",
      "mediaSession",
      "background",
      "db:read:core",
      "db:write:core"
    ],
    "contributes": {
      "services": [
        "player"
      ]
    }
  },
  "plugin-player": {
    "id": "@BBeBee/plugin-player",
    "name": "@BBeBee/plugin-player",
    "displayName": "Player",
    "description": "ctx.player — transport, queue, resolution, history.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-sources"
    ],
    "systemId": "layer-4",
    "moduleId": "playback",
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [
      "audio",
      "mediaSession",
      "background",
      "db:read:core",
      "db:write:core"
    ],
    "contributes": {
      "services": [
        "player"
      ]
    }
  },
  "@BBeBee/plugin-queue": {
    "id": "@BBeBee/plugin-queue",
    "name": "@BBeBee/plugin-queue",
    "displayName": "Queue",
    "description": "The up-next list — a view of the queue ctx.player owns.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-player"
    ],
    "systemId": "layer-4",
    "moduleId": "playback",
    "entry": {
      "main": "./dist/index.js",
      "ui": {
        "desktop": "./dist/index.js",
        "mobile": "./dist/index.js"
      }
    },
    "capabilities": [],
    "contributes": {}
  },
  "plugin-queue": {
    "id": "@BBeBee/plugin-queue",
    "name": "@BBeBee/plugin-queue",
    "displayName": "Queue",
    "description": "The up-next list — a view of the queue ctx.player owns.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-player"
    ],
    "systemId": "layer-4",
    "moduleId": "playback",
    "entry": {
      "main": "./dist/index.js",
      "ui": {
        "desktop": "./dist/index.js",
        "mobile": "./dist/index.js"
      }
    },
    "capabilities": [],
    "contributes": {}
  },
  "@BBeBee/plugin-settings": {
    "id": "@BBeBee/plugin-settings",
    "name": "@BBeBee/plugin-settings",
    "displayName": "Settings",
    "description": "Global application preferences, settings service, and settings views.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [],
    "systemId": "layer-4",
    "moduleId": "settings",
    "entry": {
      "main": "./dist/index.js",
      "ui": {
        "desktop": "./dist/index.js",
        "mobile": "./dist/index.js"
      }
    },
    "capabilities": [],
    "contributes": {
      "services": [
        "settings"
      ]
    }
  },
  "plugin-settings": {
    "id": "@BBeBee/plugin-settings",
    "name": "@BBeBee/plugin-settings",
    "displayName": "Settings",
    "description": "Global application preferences, settings service, and settings views.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [],
    "systemId": "layer-4",
    "moduleId": "settings",
    "entry": {
      "main": "./dist/index.js",
      "ui": {
        "desktop": "./dist/index.js",
        "mobile": "./dist/index.js"
      }
    },
    "capabilities": [],
    "contributes": {
      "services": [
        "settings"
      ]
    }
  },
  "@BBeBee/plugin-share": {
    "id": "@BBeBee/plugin-share",
    "name": "@BBeBee/plugin-share",
    "displayName": "Share",
    "description": "ctx.share — Song, playlist, and lyrics sharing with image steganography.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [],
    "systemId": "layer-4",
    "moduleId": "share",
    "entry": {
      "main": "./dist/index.js",
      "ui": {
        "desktop": "./dist/index.js",
        "mobile": "./dist/index.js"
      }
    },
    "capabilities": [],
    "contributes": {
      "services": [
        "share"
      ]
    }
  },
  "plugin-share": {
    "id": "@BBeBee/plugin-share",
    "name": "@BBeBee/plugin-share",
    "displayName": "Share",
    "description": "ctx.share — Song, playlist, and lyrics sharing with image steganography.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [],
    "systemId": "layer-4",
    "moduleId": "share",
    "entry": {
      "main": "./dist/index.js",
      "ui": {
        "desktop": "./dist/index.js",
        "mobile": "./dist/index.js"
      }
    },
    "capabilities": [],
    "contributes": {
      "services": [
        "share"
      ]
    }
  },
  "@BBeBee/plugin-sleep-timer": {
    "id": "@BBeBee/plugin-sleep-timer",
    "name": "@BBeBee/plugin-sleep-timer",
    "displayName": "Sleep Timer",
    "description": "ctx.sleepTimer — stops playback after a duration, at a specific time, or at track end.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-player"
    ],
    "systemId": "layer-4",
    "moduleId": "playback",
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [],
    "contributes": {
      "services": [
        "sleepTimer"
      ]
    }
  },
  "plugin-sleep-timer": {
    "id": "@BBeBee/plugin-sleep-timer",
    "name": "@BBeBee/plugin-sleep-timer",
    "displayName": "Sleep Timer",
    "description": "ctx.sleepTimer — stops playback after a duration, at a specific time, or at track end.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-player"
    ],
    "systemId": "layer-4",
    "moduleId": "playback",
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [],
    "contributes": {
      "services": [
        "sleepTimer"
      ]
    }
  },
  "@BBeBee/plugin-source-local": {
    "id": "@BBeBee/plugin-source-local",
    "name": "@BBeBee/plugin-source-local",
    "displayName": "This device",
    "description": "plugin-source-local — the files on this device, as a MediaProvider.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-sources"
    ],
    "systemId": "layer-4",
    "moduleId": "sources",
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [
      "fs:read:all",
      "db:read:core",
      "db:write:core"
    ],
    "contributes": {
      "services": [
        "sourceLocal"
      ]
    }
  },
  "plugin-source-local": {
    "id": "@BBeBee/plugin-source-local",
    "name": "@BBeBee/plugin-source-local",
    "displayName": "This device",
    "description": "plugin-source-local — the files on this device, as a MediaProvider.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-sources"
    ],
    "systemId": "layer-4",
    "moduleId": "sources",
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [
      "fs:read:all",
      "db:read:core",
      "db:write:core"
    ],
    "contributes": {
      "services": [
        "sourceLocal"
      ]
    }
  },
  "@BBeBee/plugin-source-runtime": {
    "id": "@BBeBee/plugin-source-runtime",
    "name": "@BBeBee/plugin-source-runtime",
    "displayName": "Music sources",
    "description": "plugin-source-runtime — interprets imported source strings.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-sources"
    ],
    "systemId": "layer-4",
    "moduleId": "sources",
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [
      "net:host/*",
      "db:read:core",
      "db:write:core"
    ],
    "contributes": {
      "slots": [
        "settings.sources"
      ]
    }
  },
  "plugin-source-runtime": {
    "id": "@BBeBee/plugin-source-runtime",
    "name": "@BBeBee/plugin-source-runtime",
    "displayName": "Music sources",
    "description": "plugin-source-runtime — interprets imported source strings.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-sources"
    ],
    "systemId": "layer-4",
    "moduleId": "sources",
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [
      "net:host/*",
      "db:read:core",
      "db:write:core"
    ],
    "contributes": {
      "slots": [
        "settings.sources"
      ]
    }
  },
  "@BBeBee/plugin-sources": {
    "id": "@BBeBee/plugin-sources",
    "name": "@BBeBee/plugin-sources",
    "displayName": "Sources",
    "description": "ctx.sources — imported source documents, the registry, and the catalogue cache.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [],
    "systemId": "layer-4",
    "moduleId": "sources",
    "entry": {
      "main": "./dist/index.js",
      "ui": {
        "desktop": "./dist/index.js",
        "mobile": "./dist/index.js"
      }
    },
    "capabilities": [
      "db:read:core",
      "db:write:core"
    ],
    "contributes": {
      "services": [
        "sources"
      ]
    }
  },
  "plugin-sources": {
    "id": "@BBeBee/plugin-sources",
    "name": "@BBeBee/plugin-sources",
    "displayName": "Sources",
    "description": "ctx.sources — imported source documents, the registry, and the catalogue cache.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [],
    "systemId": "layer-4",
    "moduleId": "sources",
    "entry": {
      "main": "./dist/index.js",
      "ui": {
        "desktop": "./dist/index.js",
        "mobile": "./dist/index.js"
      }
    },
    "capabilities": [
      "db:read:core",
      "db:write:core"
    ],
    "contributes": {
      "services": [
        "sources"
      ]
    }
  },
  "@BBeBee/plugin-theme": {
    "id": "@BBeBee/plugin-theme",
    "name": "@BBeBee/plugin-theme",
    "displayName": "Theme",
    "description": "Theme manager for dark music player and dynamic runtime themes.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [],
    "systemId": "layer-4",
    "moduleId": "settings",
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [],
    "contributes": {
      "services": [
        "theme"
      ]
    }
  },
  "plugin-theme": {
    "id": "@BBeBee/plugin-theme",
    "name": "@BBeBee/plugin-theme",
    "displayName": "Theme",
    "description": "Theme manager for dark music player and dynamic runtime themes.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [],
    "systemId": "layer-4",
    "moduleId": "settings",
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [],
    "contributes": {
      "services": [
        "theme"
      ]
    }
  },
  "@BBeBee/plugin-ui": {
    "id": "@BBeBee/plugin-ui",
    "name": "@BBeBee/plugin-ui",
    "displayName": "UI Registry",
    "description": "The ctx.ui contribution registry.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [],
    "systemId": "layer-4",
    "moduleId": "ui",
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [],
    "contributes": {
      "services": [
        "ui"
      ]
    }
  },
  "plugin-ui": {
    "id": "@BBeBee/plugin-ui",
    "name": "@BBeBee/plugin-ui",
    "displayName": "UI Registry",
    "description": "The ctx.ui contribution registry.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [],
    "systemId": "layer-4",
    "moduleId": "ui",
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [],
    "contributes": {
      "services": [
        "ui"
      ]
    }
  },
  "@BBeBee/plugin-visualizer": {
    "id": "@BBeBee/plugin-visualizer",
    "name": "@BBeBee/plugin-visualizer",
    "displayName": "Audio Visualizer",
    "description": "ctx.visualizer — audio spectrum and waveform analysis service.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-player"
    ],
    "systemId": "layer-4",
    "moduleId": "dsp",
    "entry": {
      "main": "./dist/index.js",
      "ui": {
        "desktop": "./dist/index.js"
      }
    },
    "capabilities": [
      "audio"
    ],
    "contributes": {
      "services": [
        "visualizer"
      ]
    }
  },
  "plugin-visualizer": {
    "id": "@BBeBee/plugin-visualizer",
    "name": "@BBeBee/plugin-visualizer",
    "displayName": "Audio Visualizer",
    "description": "ctx.visualizer — audio spectrum and waveform analysis service.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-player"
    ],
    "systemId": "layer-4",
    "moduleId": "dsp",
    "entry": {
      "main": "./dist/index.js",
      "ui": {
        "desktop": "./dist/index.js"
      }
    },
    "capabilities": [
      "audio"
    ],
    "contributes": {
      "services": [
        "visualizer"
      ]
    }
  },
  "@BBeBee/plugin-log-buffer": {
    "id": "@BBeBee/plugin-log-buffer",
    "name": "@BBeBee/plugin-log-buffer",
    "displayName": "Log Buffer",
    "description": "In-app log ring buffer.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [],
    "systemId": "layer-3",
    "moduleId": "logs",
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [],
    "contributes": {
      "services": [
        "logBuffer"
      ]
    }
  },
  "plugin-log-buffer": {
    "id": "@BBeBee/plugin-log-buffer",
    "name": "@BBeBee/plugin-log-buffer",
    "displayName": "Log Buffer",
    "description": "In-app log ring buffer.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [],
    "systemId": "layer-3",
    "moduleId": "logs",
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [],
    "contributes": {
      "services": [
        "logBuffer"
      ]
    }
  },
  "@BBeBee/plugin-log-console": {
    "id": "@BBeBee/plugin-log-console",
    "name": "@BBeBee/plugin-log-console",
    "displayName": "Console Logs",
    "description": "Development console transport.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-log-buffer"
    ],
    "systemId": "layer-3",
    "moduleId": "logs",
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [],
    "contributes": {}
  },
  "plugin-log-console": {
    "id": "@BBeBee/plugin-log-console",
    "name": "@BBeBee/plugin-log-console",
    "displayName": "Console Logs",
    "description": "Development console transport.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-log-buffer"
    ],
    "systemId": "layer-3",
    "moduleId": "logs",
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [],
    "contributes": {}
  },
  "@BBeBee/plugin-log-file": {
    "id": "@BBeBee/plugin-log-file",
    "name": "@BBeBee/plugin-log-file",
    "displayName": "Log File",
    "description": "Rotating NDJSON log file.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-log-buffer"
    ],
    "systemId": "layer-3",
    "moduleId": "logs",
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [
      "fs:write:logs",
      "fs:read:logs"
    ],
    "contributes": {}
  },
  "plugin-log-file": {
    "id": "@BBeBee/plugin-log-file",
    "name": "@BBeBee/plugin-log-file",
    "displayName": "Log File",
    "description": "Rotating NDJSON log file.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-log-buffer"
    ],
    "systemId": "layer-3",
    "moduleId": "logs",
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [
      "fs:write:logs",
      "fs:read:logs"
    ],
    "contributes": {}
  },
  "@BBeBee/plugin-album-ui-desktop": {
    "id": "@BBeBee/plugin-album-ui-desktop",
    "name": "@BBeBee/plugin-album-ui-desktop",
    "displayName": "Album UI (Desktop)",
    "description": "React DOM views for @BBeBee/plugin-album.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-ui",
      "@BBeBee/plugin-album"
    ],
    "systemId": "layer-5",
    "moduleId": "storage",
    "platforms": [
      "desktop"
    ],
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [],
    "contributes": {}
  },
  "plugin-album-ui-desktop": {
    "id": "@BBeBee/plugin-album-ui-desktop",
    "name": "@BBeBee/plugin-album-ui-desktop",
    "displayName": "Album UI (Desktop)",
    "description": "React DOM views for @BBeBee/plugin-album.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-ui",
      "@BBeBee/plugin-album"
    ],
    "systemId": "layer-5",
    "moduleId": "storage",
    "platforms": [
      "desktop"
    ],
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [],
    "contributes": {}
  },
  "@BBeBee/plugin-album-ui-mobile": {
    "id": "@BBeBee/plugin-album-ui-mobile",
    "name": "@BBeBee/plugin-album-ui-mobile",
    "displayName": "Album UI (Mobile)",
    "description": "React Native views for @BBeBee/plugin-album.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-ui",
      "@BBeBee/plugin-album"
    ],
    "systemId": "layer-5",
    "moduleId": "storage",
    "platforms": [
      "mobile"
    ],
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [],
    "contributes": {}
  },
  "plugin-album-ui-mobile": {
    "id": "@BBeBee/plugin-album-ui-mobile",
    "name": "@BBeBee/plugin-album-ui-mobile",
    "displayName": "Album UI (Mobile)",
    "description": "React Native views for @BBeBee/plugin-album.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-ui",
      "@BBeBee/plugin-album"
    ],
    "systemId": "layer-5",
    "moduleId": "storage",
    "platforms": [
      "mobile"
    ],
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [],
    "contributes": {}
  },
  "@BBeBee/plugin-desktop-lyrics-ui-desktop": {
    "id": "@BBeBee/plugin-desktop-lyrics-ui-desktop",
    "name": "@BBeBee/plugin-desktop-lyrics-ui-desktop",
    "displayName": "Desktop Lyrics UI (Desktop)",
    "description": "Desktop floating lyrics views for @BBeBee/plugin-desktop-lyrics.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-ui",
      "@BBeBee/plugin-desktop-lyrics"
    ],
    "systemId": "layer-5",
    "moduleId": "lyrics",
    "platforms": [
      "desktop"
    ],
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [],
    "contributes": {}
  },
  "plugin-desktop-lyrics-ui-desktop": {
    "id": "@BBeBee/plugin-desktop-lyrics-ui-desktop",
    "name": "@BBeBee/plugin-desktop-lyrics-ui-desktop",
    "displayName": "Desktop Lyrics UI (Desktop)",
    "description": "Desktop floating lyrics views for @BBeBee/plugin-desktop-lyrics.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-ui",
      "@BBeBee/plugin-desktop-lyrics"
    ],
    "systemId": "layer-5",
    "moduleId": "lyrics",
    "platforms": [
      "desktop"
    ],
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [],
    "contributes": {}
  },
  "@BBeBee/plugin-download-ui-desktop": {
    "id": "@BBeBee/plugin-download-ui-desktop",
    "name": "@BBeBee/plugin-download-ui-desktop",
    "displayName": "Download UI (Desktop)",
    "description": "React DOM views for plugin-download.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-ui",
      "@BBeBee/plugin-download"
    ],
    "systemId": "layer-5",
    "moduleId": "storage",
    "platforms": [
      "desktop"
    ],
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [],
    "contributes": {}
  },
  "plugin-download-ui-desktop": {
    "id": "@BBeBee/plugin-download-ui-desktop",
    "name": "@BBeBee/plugin-download-ui-desktop",
    "displayName": "Download UI (Desktop)",
    "description": "React DOM views for plugin-download.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-ui",
      "@BBeBee/plugin-download"
    ],
    "systemId": "layer-5",
    "moduleId": "storage",
    "platforms": [
      "desktop"
    ],
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [],
    "contributes": {}
  },
  "@BBeBee/plugin-download-ui-mobile": {
    "id": "@BBeBee/plugin-download-ui-mobile",
    "name": "@BBeBee/plugin-download-ui-mobile",
    "displayName": "Download UI (Mobile)",
    "description": "React Native views for plugin-download.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-ui",
      "@BBeBee/plugin-download"
    ],
    "systemId": "layer-5",
    "moduleId": "storage",
    "platforms": [
      "mobile"
    ],
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [],
    "contributes": {}
  },
  "plugin-download-ui-mobile": {
    "id": "@BBeBee/plugin-download-ui-mobile",
    "name": "@BBeBee/plugin-download-ui-mobile",
    "displayName": "Download UI (Mobile)",
    "description": "React Native views for plugin-download.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-ui",
      "@BBeBee/plugin-download"
    ],
    "systemId": "layer-5",
    "moduleId": "storage",
    "platforms": [
      "mobile"
    ],
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [],
    "contributes": {}
  },
  "@BBeBee/plugin-dsp-ui-desktop": {
    "id": "@BBeBee/plugin-dsp-ui-desktop",
    "name": "@BBeBee/plugin-dsp-ui-desktop",
    "displayName": "Dsp UI (Desktop)",
    "description": "Desktop views for @BBeBee/plugin-dsp (DSP Chain Editor).",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-ui",
      "@BBeBee/plugin-dsp"
    ],
    "systemId": "layer-5",
    "moduleId": "dsp",
    "platforms": [
      "desktop"
    ],
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [],
    "contributes": {}
  },
  "plugin-dsp-ui-desktop": {
    "id": "@BBeBee/plugin-dsp-ui-desktop",
    "name": "@BBeBee/plugin-dsp-ui-desktop",
    "displayName": "Dsp UI (Desktop)",
    "description": "Desktop views for @BBeBee/plugin-dsp (DSP Chain Editor).",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-ui",
      "@BBeBee/plugin-dsp"
    ],
    "systemId": "layer-5",
    "moduleId": "dsp",
    "platforms": [
      "desktop"
    ],
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [],
    "contributes": {}
  },
  "@BBeBee/plugin-dsp-ui-mobile": {
    "id": "@BBeBee/plugin-dsp-ui-mobile",
    "name": "@BBeBee/plugin-dsp-ui-mobile",
    "displayName": "Dsp UI (Mobile)",
    "description": "Mobile React Native views for @BBeBee/plugin-dsp (DSP Chain Editor).",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-ui",
      "@BBeBee/plugin-dsp"
    ],
    "systemId": "layer-5",
    "moduleId": "dsp",
    "platforms": [
      "mobile"
    ],
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [],
    "contributes": {}
  },
  "plugin-dsp-ui-mobile": {
    "id": "@BBeBee/plugin-dsp-ui-mobile",
    "name": "@BBeBee/plugin-dsp-ui-mobile",
    "displayName": "Dsp UI (Mobile)",
    "description": "Mobile React Native views for @BBeBee/plugin-dsp (DSP Chain Editor).",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-ui",
      "@BBeBee/plugin-dsp"
    ],
    "systemId": "layer-5",
    "moduleId": "dsp",
    "platforms": [
      "mobile"
    ],
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [],
    "contributes": {}
  },
  "@BBeBee/plugin-history-ui-desktop": {
    "id": "@BBeBee/plugin-history-ui-desktop",
    "name": "@BBeBee/plugin-history-ui-desktop",
    "displayName": "History UI (Desktop)",
    "description": "React DOM views for @BBeBee/plugin-history.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-ui",
      "@BBeBee/plugin-history"
    ],
    "systemId": "layer-5",
    "moduleId": "storage",
    "platforms": [
      "desktop"
    ],
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [],
    "contributes": {}
  },
  "plugin-history-ui-desktop": {
    "id": "@BBeBee/plugin-history-ui-desktop",
    "name": "@BBeBee/plugin-history-ui-desktop",
    "displayName": "History UI (Desktop)",
    "description": "React DOM views for @BBeBee/plugin-history.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-ui",
      "@BBeBee/plugin-history"
    ],
    "systemId": "layer-5",
    "moduleId": "storage",
    "platforms": [
      "desktop"
    ],
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [],
    "contributes": {}
  },
  "@BBeBee/plugin-history-ui-mobile": {
    "id": "@BBeBee/plugin-history-ui-mobile",
    "name": "@BBeBee/plugin-history-ui-mobile",
    "displayName": "History UI (Mobile)",
    "description": "React Native views for @BBeBee/plugin-history.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-ui",
      "@BBeBee/plugin-history"
    ],
    "systemId": "layer-5",
    "moduleId": "storage",
    "platforms": [
      "mobile"
    ],
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [],
    "contributes": {}
  },
  "plugin-history-ui-mobile": {
    "id": "@BBeBee/plugin-history-ui-mobile",
    "name": "@BBeBee/plugin-history-ui-mobile",
    "displayName": "History UI (Mobile)",
    "description": "React Native views for @BBeBee/plugin-history.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-ui",
      "@BBeBee/plugin-history"
    ],
    "systemId": "layer-5",
    "moduleId": "storage",
    "platforms": [
      "mobile"
    ],
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [],
    "contributes": {}
  },
  "@BBeBee/plugin-inspector-ui-desktop": {
    "id": "@BBeBee/plugin-inspector-ui-desktop",
    "name": "@BBeBee/plugin-inspector-ui-desktop",
    "displayName": "Inspector UI (Desktop)",
    "description": "React DOM view for the plugin inspector.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-ui",
      "@BBeBee/plugin-inspector"
    ],
    "systemId": "layer-5",
    "moduleId": "inspector",
    "platforms": [
      "desktop"
    ],
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [],
    "contributes": {}
  },
  "plugin-inspector-ui-desktop": {
    "id": "@BBeBee/plugin-inspector-ui-desktop",
    "name": "@BBeBee/plugin-inspector-ui-desktop",
    "displayName": "Inspector UI (Desktop)",
    "description": "React DOM view for the plugin inspector.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-ui",
      "@BBeBee/plugin-inspector"
    ],
    "systemId": "layer-5",
    "moduleId": "inspector",
    "platforms": [
      "desktop"
    ],
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [],
    "contributes": {}
  },
  "@BBeBee/plugin-library-ui-desktop": {
    "id": "@BBeBee/plugin-library-ui-desktop",
    "name": "@BBeBee/plugin-library-ui-desktop",
    "displayName": "Library UI (Desktop)",
    "description": "React DOM views for @BBeBee/plugin-library.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-ui",
      "@BBeBee/plugin-library"
    ],
    "systemId": "layer-5",
    "moduleId": "storage",
    "platforms": [
      "desktop"
    ],
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [],
    "contributes": {}
  },
  "plugin-library-ui-desktop": {
    "id": "@BBeBee/plugin-library-ui-desktop",
    "name": "@BBeBee/plugin-library-ui-desktop",
    "displayName": "Library UI (Desktop)",
    "description": "React DOM views for @BBeBee/plugin-library.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-ui",
      "@BBeBee/plugin-library"
    ],
    "systemId": "layer-5",
    "moduleId": "storage",
    "platforms": [
      "desktop"
    ],
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [],
    "contributes": {}
  },
  "@BBeBee/plugin-library-ui-mobile": {
    "id": "@BBeBee/plugin-library-ui-mobile",
    "name": "@BBeBee/plugin-library-ui-mobile",
    "displayName": "Library UI (Mobile)",
    "description": "React Native views for @BBeBee/plugin-library.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-ui",
      "@BBeBee/plugin-library"
    ],
    "systemId": "layer-5",
    "moduleId": "storage",
    "platforms": [
      "mobile"
    ],
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [],
    "contributes": {}
  },
  "plugin-library-ui-mobile": {
    "id": "@BBeBee/plugin-library-ui-mobile",
    "name": "@BBeBee/plugin-library-ui-mobile",
    "displayName": "Library UI (Mobile)",
    "description": "React Native views for @BBeBee/plugin-library.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-ui",
      "@BBeBee/plugin-library"
    ],
    "systemId": "layer-5",
    "moduleId": "storage",
    "platforms": [
      "mobile"
    ],
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [],
    "contributes": {}
  },
  "@BBeBee/plugin-local-scanner-ui-desktop": {
    "id": "@BBeBee/plugin-local-scanner-ui-desktop",
    "name": "@BBeBee/plugin-local-scanner-ui-desktop",
    "displayName": "Local Scanner UI (Desktop)",
    "description": "React DOM views for plugin-local-scanner.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-ui",
      "@BBeBee/plugin-local-scanner"
    ],
    "systemId": "layer-5",
    "moduleId": "storage",
    "platforms": [
      "desktop"
    ],
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [],
    "contributes": {}
  },
  "plugin-local-scanner-ui-desktop": {
    "id": "@BBeBee/plugin-local-scanner-ui-desktop",
    "name": "@BBeBee/plugin-local-scanner-ui-desktop",
    "displayName": "Local Scanner UI (Desktop)",
    "description": "React DOM views for plugin-local-scanner.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-ui",
      "@BBeBee/plugin-local-scanner"
    ],
    "systemId": "layer-5",
    "moduleId": "storage",
    "platforms": [
      "desktop"
    ],
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [],
    "contributes": {}
  },
  "@BBeBee/plugin-local-scanner-ui-mobile": {
    "id": "@BBeBee/plugin-local-scanner-ui-mobile",
    "name": "@BBeBee/plugin-local-scanner-ui-mobile",
    "displayName": "Local Scanner UI (Mobile)",
    "description": "React Native views for plugin-local-scanner.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-ui",
      "@BBeBee/plugin-local-scanner"
    ],
    "systemId": "layer-5",
    "moduleId": "storage",
    "platforms": [
      "mobile"
    ],
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [],
    "contributes": {}
  },
  "plugin-local-scanner-ui-mobile": {
    "id": "@BBeBee/plugin-local-scanner-ui-mobile",
    "name": "@BBeBee/plugin-local-scanner-ui-mobile",
    "displayName": "Local Scanner UI (Mobile)",
    "description": "React Native views for plugin-local-scanner.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-ui",
      "@BBeBee/plugin-local-scanner"
    ],
    "systemId": "layer-5",
    "moduleId": "storage",
    "platforms": [
      "mobile"
    ],
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [],
    "contributes": {}
  },
  "@BBeBee/plugin-lyrics-ui-desktop": {
    "id": "@BBeBee/plugin-lyrics-ui-desktop",
    "name": "@BBeBee/plugin-lyrics-ui-desktop",
    "displayName": "Lyrics UI (Desktop)",
    "description": "Desktop views for @BBeBee/plugin-lyrics (Lyrics Panel).",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-ui",
      "@BBeBee/plugin-lyrics"
    ],
    "systemId": "layer-5",
    "moduleId": "lyrics",
    "platforms": [
      "desktop"
    ],
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [],
    "contributes": {}
  },
  "plugin-lyrics-ui-desktop": {
    "id": "@BBeBee/plugin-lyrics-ui-desktop",
    "name": "@BBeBee/plugin-lyrics-ui-desktop",
    "displayName": "Lyrics UI (Desktop)",
    "description": "Desktop views for @BBeBee/plugin-lyrics (Lyrics Panel).",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-ui",
      "@BBeBee/plugin-lyrics"
    ],
    "systemId": "layer-5",
    "moduleId": "lyrics",
    "platforms": [
      "desktop"
    ],
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [],
    "contributes": {}
  },
  "@BBeBee/plugin-mini-player-ui-desktop": {
    "id": "@BBeBee/plugin-mini-player-ui-desktop",
    "name": "@BBeBee/plugin-mini-player-ui-desktop",
    "displayName": "Mini Player UI (Desktop)",
    "description": "Desktop UI views for @BBeBee/plugin-mini-player.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-ui",
      "@BBeBee/plugin-mini-player"
    ],
    "systemId": "layer-5",
    "moduleId": "playback",
    "platforms": [
      "desktop"
    ],
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [],
    "contributes": {}
  },
  "plugin-mini-player-ui-desktop": {
    "id": "@BBeBee/plugin-mini-player-ui-desktop",
    "name": "@BBeBee/plugin-mini-player-ui-desktop",
    "displayName": "Mini Player UI (Desktop)",
    "description": "Desktop UI views for @BBeBee/plugin-mini-player.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-ui",
      "@BBeBee/plugin-mini-player"
    ],
    "systemId": "layer-5",
    "moduleId": "playback",
    "platforms": [
      "desktop"
    ],
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [],
    "contributes": {}
  },
  "@BBeBee/plugin-now-playing-ui-desktop": {
    "id": "@BBeBee/plugin-now-playing-ui-desktop",
    "name": "@BBeBee/plugin-now-playing-ui-desktop",
    "displayName": "Now Playing UI (Desktop)",
    "description": "React DOM views for @BBeBee/plugin-now-playing.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-ui",
      "@BBeBee/plugin-now-playing"
    ],
    "systemId": "layer-5",
    "moduleId": "playback",
    "platforms": [
      "desktop"
    ],
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [],
    "contributes": {}
  },
  "plugin-now-playing-ui-desktop": {
    "id": "@BBeBee/plugin-now-playing-ui-desktop",
    "name": "@BBeBee/plugin-now-playing-ui-desktop",
    "displayName": "Now Playing UI (Desktop)",
    "description": "React DOM views for @BBeBee/plugin-now-playing.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-ui",
      "@BBeBee/plugin-now-playing"
    ],
    "systemId": "layer-5",
    "moduleId": "playback",
    "platforms": [
      "desktop"
    ],
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [],
    "contributes": {}
  },
  "@BBeBee/plugin-now-playing-ui-mobile": {
    "id": "@BBeBee/plugin-now-playing-ui-mobile",
    "name": "@BBeBee/plugin-now-playing-ui-mobile",
    "displayName": "Now Playing UI (Mobile)",
    "description": "React Native views for @BBeBee/plugin-now-playing.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-ui",
      "@BBeBee/plugin-now-playing"
    ],
    "systemId": "layer-5",
    "moduleId": "playback",
    "platforms": [
      "mobile"
    ],
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [],
    "contributes": {}
  },
  "plugin-now-playing-ui-mobile": {
    "id": "@BBeBee/plugin-now-playing-ui-mobile",
    "name": "@BBeBee/plugin-now-playing-ui-mobile",
    "displayName": "Now Playing UI (Mobile)",
    "description": "React Native views for @BBeBee/plugin-now-playing.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-ui",
      "@BBeBee/plugin-now-playing"
    ],
    "systemId": "layer-5",
    "moduleId": "playback",
    "platforms": [
      "mobile"
    ],
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [],
    "contributes": {}
  },
  "@BBeBee/plugin-queue-ui-desktop": {
    "id": "@BBeBee/plugin-queue-ui-desktop",
    "name": "@BBeBee/plugin-queue-ui-desktop",
    "displayName": "Queue UI (Desktop)",
    "description": "React DOM views for @BBeBee/plugin-queue.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-ui",
      "@BBeBee/plugin-queue"
    ],
    "systemId": "layer-5",
    "moduleId": "playback",
    "platforms": [
      "desktop"
    ],
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [],
    "contributes": {}
  },
  "plugin-queue-ui-desktop": {
    "id": "@BBeBee/plugin-queue-ui-desktop",
    "name": "@BBeBee/plugin-queue-ui-desktop",
    "displayName": "Queue UI (Desktop)",
    "description": "React DOM views for @BBeBee/plugin-queue.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-ui",
      "@BBeBee/plugin-queue"
    ],
    "systemId": "layer-5",
    "moduleId": "playback",
    "platforms": [
      "desktop"
    ],
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [],
    "contributes": {}
  },
  "@BBeBee/plugin-queue-ui-mobile": {
    "id": "@BBeBee/plugin-queue-ui-mobile",
    "name": "@BBeBee/plugin-queue-ui-mobile",
    "displayName": "Queue UI (Mobile)",
    "description": "React Native views for @BBeBee/plugin-queue.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-ui",
      "@BBeBee/plugin-queue"
    ],
    "systemId": "layer-5",
    "moduleId": "playback",
    "platforms": [
      "mobile"
    ],
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [],
    "contributes": {}
  },
  "plugin-queue-ui-mobile": {
    "id": "@BBeBee/plugin-queue-ui-mobile",
    "name": "@BBeBee/plugin-queue-ui-mobile",
    "displayName": "Queue UI (Mobile)",
    "description": "React Native views for @BBeBee/plugin-queue.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-ui",
      "@BBeBee/plugin-queue"
    ],
    "systemId": "layer-5",
    "moduleId": "playback",
    "platforms": [
      "mobile"
    ],
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [],
    "contributes": {}
  },
  "@BBeBee/plugin-settings-ui-desktop": {
    "id": "@BBeBee/plugin-settings-ui-desktop",
    "name": "@BBeBee/plugin-settings-ui-desktop",
    "displayName": "Settings UI (Desktop)",
    "description": "React DOM views for @BBeBee/plugin-settings.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-ui",
      "@BBeBee/plugin-settings"
    ],
    "systemId": "layer-5",
    "moduleId": "settings",
    "platforms": [
      "desktop"
    ],
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [],
    "contributes": {}
  },
  "plugin-settings-ui-desktop": {
    "id": "@BBeBee/plugin-settings-ui-desktop",
    "name": "@BBeBee/plugin-settings-ui-desktop",
    "displayName": "Settings UI (Desktop)",
    "description": "React DOM views for @BBeBee/plugin-settings.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-ui",
      "@BBeBee/plugin-settings"
    ],
    "systemId": "layer-5",
    "moduleId": "settings",
    "platforms": [
      "desktop"
    ],
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [],
    "contributes": {}
  },
  "@BBeBee/plugin-settings-ui-mobile": {
    "id": "@BBeBee/plugin-settings-ui-mobile",
    "name": "@BBeBee/plugin-settings-ui-mobile",
    "displayName": "Settings UI (Mobile)",
    "description": "React Native views for @BBeBee/plugin-settings.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-ui",
      "@BBeBee/plugin-settings"
    ],
    "systemId": "layer-5",
    "moduleId": "settings",
    "platforms": [
      "mobile"
    ],
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [],
    "contributes": {}
  },
  "plugin-settings-ui-mobile": {
    "id": "@BBeBee/plugin-settings-ui-mobile",
    "name": "@BBeBee/plugin-settings-ui-mobile",
    "displayName": "Settings UI (Mobile)",
    "description": "React Native views for @BBeBee/plugin-settings.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-ui",
      "@BBeBee/plugin-settings"
    ],
    "systemId": "layer-5",
    "moduleId": "settings",
    "platforms": [
      "mobile"
    ],
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [],
    "contributes": {}
  },
  "@BBeBee/plugin-share-ui-desktop": {
    "id": "@BBeBee/plugin-share-ui-desktop",
    "name": "@BBeBee/plugin-share-ui-desktop",
    "displayName": "Share UI (Desktop)",
    "description": "Desktop views for @BBeBee/plugin-share (Spotify-style share modals & steganography reader).",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-ui",
      "@BBeBee/plugin-share"
    ],
    "systemId": "layer-5",
    "moduleId": "share",
    "platforms": [
      "desktop"
    ],
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [],
    "contributes": {}
  },
  "plugin-share-ui-desktop": {
    "id": "@BBeBee/plugin-share-ui-desktop",
    "name": "@BBeBee/plugin-share-ui-desktop",
    "displayName": "Share UI (Desktop)",
    "description": "Desktop views for @BBeBee/plugin-share (Spotify-style share modals & steganography reader).",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-ui",
      "@BBeBee/plugin-share"
    ],
    "systemId": "layer-5",
    "moduleId": "share",
    "platforms": [
      "desktop"
    ],
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [],
    "contributes": {}
  },
  "@BBeBee/plugin-share-ui-mobile": {
    "id": "@BBeBee/plugin-share-ui-mobile",
    "name": "@BBeBee/plugin-share-ui-mobile",
    "displayName": "Share UI (Mobile)",
    "description": "React Native views for @BBeBee/plugin-share — share codes and the import reader.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-ui",
      "@BBeBee/plugin-share"
    ],
    "systemId": "layer-5",
    "moduleId": "share",
    "platforms": [
      "mobile"
    ],
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [],
    "contributes": {}
  },
  "plugin-share-ui-mobile": {
    "id": "@BBeBee/plugin-share-ui-mobile",
    "name": "@BBeBee/plugin-share-ui-mobile",
    "displayName": "Share UI (Mobile)",
    "description": "React Native views for @BBeBee/plugin-share — share codes and the import reader.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-ui",
      "@BBeBee/plugin-share"
    ],
    "systemId": "layer-5",
    "moduleId": "share",
    "platforms": [
      "mobile"
    ],
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [],
    "contributes": {}
  },
  "@BBeBee/plugin-sources-ui-desktop": {
    "id": "@BBeBee/plugin-sources-ui-desktop",
    "name": "@BBeBee/plugin-sources-ui-desktop",
    "displayName": "Sources UI (Desktop)",
    "description": "React DOM views for plugin-sources.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-ui",
      "@BBeBee/plugin-sources"
    ],
    "systemId": "layer-5",
    "moduleId": "sources",
    "platforms": [
      "desktop"
    ],
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [],
    "contributes": {}
  },
  "plugin-sources-ui-desktop": {
    "id": "@BBeBee/plugin-sources-ui-desktop",
    "name": "@BBeBee/plugin-sources-ui-desktop",
    "displayName": "Sources UI (Desktop)",
    "description": "React DOM views for plugin-sources.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-ui",
      "@BBeBee/plugin-sources"
    ],
    "systemId": "layer-5",
    "moduleId": "sources",
    "platforms": [
      "desktop"
    ],
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [],
    "contributes": {}
  },
  "@BBeBee/plugin-sources-ui-mobile": {
    "id": "@BBeBee/plugin-sources-ui-mobile",
    "name": "@BBeBee/plugin-sources-ui-mobile",
    "displayName": "Sources UI (Mobile)",
    "description": "React Native views for plugin-sources.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-ui",
      "@BBeBee/plugin-sources"
    ],
    "systemId": "layer-5",
    "moduleId": "sources",
    "platforms": [
      "mobile"
    ],
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [],
    "contributes": {}
  },
  "plugin-sources-ui-mobile": {
    "id": "@BBeBee/plugin-sources-ui-mobile",
    "name": "@BBeBee/plugin-sources-ui-mobile",
    "displayName": "Sources UI (Mobile)",
    "description": "React Native views for plugin-sources.",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-ui",
      "@BBeBee/plugin-sources"
    ],
    "systemId": "layer-5",
    "moduleId": "sources",
    "platforms": [
      "mobile"
    ],
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [],
    "contributes": {}
  },
  "@BBeBee/plugin-visualizer-ui-desktop": {
    "id": "@BBeBee/plugin-visualizer-ui-desktop",
    "name": "@BBeBee/plugin-visualizer-ui-desktop",
    "displayName": "Visualizer UI (Desktop)",
    "description": "Desktop views for @BBeBee/plugin-visualizer (Audio Visualizer).",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-ui",
      "@BBeBee/plugin-visualizer"
    ],
    "systemId": "layer-5",
    "moduleId": "dsp",
    "platforms": [
      "desktop"
    ],
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [],
    "contributes": {}
  },
  "plugin-visualizer-ui-desktop": {
    "id": "@BBeBee/plugin-visualizer-ui-desktop",
    "name": "@BBeBee/plugin-visualizer-ui-desktop",
    "displayName": "Visualizer UI (Desktop)",
    "description": "Desktop views for @BBeBee/plugin-visualizer (Audio Visualizer).",
    "version": "0.0.0",
    "author": "BBeBee Team",
    "engines": {
      "BBeBee": "^0.1.0"
    },
    "enabled": true,
    "dependencies": [
      "@BBeBee/plugin-ui",
      "@BBeBee/plugin-visualizer"
    ],
    "systemId": "layer-5",
    "moduleId": "dsp",
    "platforms": [
      "desktop"
    ],
    "entry": {
      "main": "./dist/index.js"
    },
    "capabilities": [],
    "contributes": {}
  }
}
