/**
 * Codegen for the static plugin registry.
 *
 * Metro cannot resolve a module path computed at runtime, so every plugin
 * import on mobile has to be statically analysable. This scans the workspace
 * for packages carrying a `BBeBee.plugin.json` and emits a module of literal
 * `import` statements — the shape `plugin-loader-static` consumes.
 *
 * The output is committed, so a clean checkout builds without running codegen
 * first and CI can assert the file is up to date rather than regenerating it.
 *
 * See docs/03-plugin-system.md §6.1.
 */

import { readdir, readFile, writeFile } from 'node:fs/promises'
import { join, relative } from 'node:path'
import type { PluginManifest } from '@BBeBee/protocol'

export interface DiscoveredPlugin {
  manifest: PluginManifest
  /** Package directory, absolute. */
  dir: string
}

export interface GenerateOptions {
  /** Workspace root. */
  root: string
  /** Directories to scan, relative to root. */
  packagesDirs?: string[]
  /** Which UI entrypoint to wire up. */
  target: 'mobile' | 'desktop'
  /** Where to write the generated module. */
  outFile: string
}

/** Find every workspace package that declares itself a BBeBee plugin. */
export async function discover(
  root: string,
  packagesDirs: string[] = ['packages'],
): Promise<DiscoveredPlugin[]> {
  const found: DiscoveredPlugin[] = []

  for (const rel of packagesDirs) {
    const base = join(root, rel)
    let entries: string[]
    try {
      entries = await readdir(base)
    } catch {
      continue
    }

    for (const entry of entries.sort()) {
      const dir = join(base, entry)
      try {
        const raw = await readFile(join(dir, 'BBeBee.plugin.json'), 'utf8')
        found.push({ manifest: JSON.parse(raw) as PluginManifest, dir })
      } catch {
        // Not a plugin package. The overwhelming majority of entries.
      }
    }
  }
  return found
}

/**
 * Render the registry module.
 *
 * Import identifiers are derived from the package id and deduplicated, because
 * two packages differing only in punctuation would otherwise emit the same
 * binding and fail to compile — loudly, but confusingly.
 */
/**
 * Keep only the plugins that belong in this shell.
 *
 * A manifest with no `platforms` runs everywhere — that is the default and the
 * point of the architecture. The exceptions are the `core-*` implementations,
 * which are platform-specific by nature: without this the mobile registry
 * imported Electron, and nothing said so, because a bundler resolving
 * `electron` in React Native fails at run time rather than at build time.
 */
export function forTarget(
  plugins: DiscoveredPlugin[],
  target: 'mobile' | 'desktop',
): DiscoveredPlugin[] {
  return plugins.filter((p) => !p.manifest.platforms || p.manifest.platforms.includes(target))
}

export function render(plugins: DiscoveredPlugin[], target: 'mobile' | 'desktop'): string {
  const used = new Set<string>()
  const identFor = (id: string): string => {
    const base = id
      .replace(/^@[^/]+\//, '')
      .replace(/[^a-zA-Z0-9]+(.)?/g, (_, c: string | undefined) => (c ? c.toUpperCase() : ''))
    let ident = /^[a-zA-Z_]/.test(base) ? base : `p${base}`
    let n = 2
    while (used.has(ident)) ident = `${base}${n++}`
    used.add(ident)
    return ident
  }

  const rows = plugins.map((p) => ({
    id: p.manifest.id,
    ident: identFor(p.manifest.id),
    ui: p.manifest.entry.ui?.[target],
    manifest: p.manifest,
  }))

  const lines: string[] = [
    '// GENERATED by @BBeBee/tooling-gen-plugins — do not edit.',
    `// Target: ${target}. Run \`pnpm gen:plugins\` to refresh.`,
    '',
    "import type { PluginRegistry } from '@BBeBee/kernel'",
  ]

  for (const row of rows) {
    lines.push(`import ${row.ident} from '${row.id}'`)
    if (row.ui) lines.push(`import ${row.ident}Ui from '${row.id}-ui-${target}'`)
  }

  lines.push('', 'export const bundled: PluginRegistry = {')
  for (const row of rows) {
    lines.push(`  ${JSON.stringify(row.id)}: {`)
    lines.push(`    plugin: ${row.ident},`)
    lines.push(`    manifest: ${JSON.stringify(row.manifest)},`)
    // Workspace plugins are first-party, so the capability gate trusts their
    // manifests without a user grant (docs/03 §7).
    lines.push('    builtin: true,')
    lines.push('  },')
    if (row.ui) {
      const uiId = `${row.id}-ui-${target}`
      lines.push(`  ${JSON.stringify(uiId)}: {`)
      lines.push(`    plugin: ${row.ident}Ui,`)
      lines.push(
        `    manifest: ${JSON.stringify({
          ...row.manifest,
          id: uiId,
          displayName: `${row.manifest.displayName} (${target} views)`,
          capabilities: [],
          entry: { main: row.ui },
        })},`,
      )
      lines.push('    builtin: true,')
      lines.push('  },')
    }
  }
  lines.push('}', '')
  return lines.join('\n')
}

export async function generate(options: GenerateOptions): Promise<string> {
  const plugins = await discover(options.root, options.packagesDirs)
  const source = render(forTarget(plugins, options.target), options.target)
  await writeFile(options.outFile, source, 'utf8')
  return relative(options.root, options.outFile)
}
